import React,{useState} from 'react';
import { DriverStanding, ConstructorStanding, DataProvenance } from '../../types/f1';
import { EmptyState } from '../shared/EmptyState';
interface Props {driverStandings:DriverStanding[];constructorStandings:ConstructorStanding[];selectedSeason:number;onSelectSeason:(season:number)=>void;availableSeasons?:number[];provenance?:DataProvenance;isLoading?:boolean;error?:string|null}
export const StandingsWorkstation:React.FC<Props>=({driverStandings,constructorStandings,selectedSeason,onSelectSeason,availableSeasons=[2026,2025,2024,2023,2022],isLoading,error})=>{
 const [tab,setTab]=useState<'drivers'|'constructors'>('drivers'); const rows:any[]=tab==='drivers'?driverStandings:constructorStandings;
 return <div className="f1-info-page"><div className="f1-page-hero"><div><span className="f1-page-kicker">CHAMPIONSHIP</span><h1>STANDINGS</h1><p>Championship order, points, wins and gap to the leader.</p></div><div className="f1-season-switch">{availableSeasons.map(s=><button key={s} onClick={()=>onSelectSeason(s)} className={selectedSeason===s?'is-active':''}>{s}</button>)}</div></div>
 <div className="f1-tabs"><button className={tab==='drivers'?'is-active':''} onClick={()=>setTab('drivers')}>DRIVERS</button><button className={tab==='constructors'?'is-active':''} onClick={()=>setTab('constructors')}>CONSTRUCTORS</button></div>
 {isLoading?<div className="f1-empty-card">LOADING {selectedSeason} CHAMPIONSHIP…</div>:error?<EmptyState type="not-found" title="STANDINGS UNAVAILABLE" message={error}/>:rows.length===0?<EmptyState type="no-data" title="NO POINTS RECORDED" message="No championship classification is available."/>:<><div className="f1-podium-strip">{rows.slice(0,3).map((r,i)=>{const person=tab==='drivers'?r.driver:r.team;return <div key={person.id} className={'f1-podium-card p'+(i+1)} style={{'--podium-color':person.color||r.driver?.teamColor||r.team?.color} as React.CSSProperties}><span>P{i+1}</span><strong>{tab==='drivers'?r.driver.code:r.team.name}</strong><b>{r.points}</b><small>POINTS</small></div>})}</div>
 <div className="f1-standing-list">{rows.map((r,i)=>{const name=tab==='drivers'?r.driver.fullName:r.team.name;const code=tab==='drivers'?r.driver.code:r.team.name;const color=tab==='drivers'?r.driver.teamColor:r.team.color;return <div key={tab==='drivers'?r.driver.id:r.team.id} className="f1-standing-row"><span className="f1-standing-pos">{String(r.position??i+1).padStart(2,'0')}</span><span className="f1-standing-accent" style={{background:color}}/><div className="f1-standing-person">{tab==='drivers'&&r.driver.headshotUrl?<img src={r.driver.headshotUrl} alt="" loading="lazy"/>:<span className="f1-standing-avatar">{code.slice(0,3)}</span>}<div><b>{name}</b><small>{tab==='drivers'?r.driver.teamName:r.team.powerUnit}</small></div></div><strong className="f1-standing-points">{r.points}</strong><span className="f1-standing-behind">{r.behindLeader===0?'LEADER':'-'+r.behindLeader}</span><span className="f1-standing-wins">{r.wins} W</span></div>})}</div></>}
 </div>;
};
