import React,{useState} from 'react';
import { Team, Driver, DataProvenance } from '../../types/f1';
import { EmptyState } from '../shared/EmptyState';
import { Star, X } from 'lucide-react';
interface Props { teams:Team[]; drivers?:Driver[]; selectedSeason:number; onSelectSeason:(season:number)=>void; availableSeasons?:number[]; provenance?:DataProvenance; isLoading?:boolean; error?:string|null; favoriteTeamId?:string|null; onSelectFavorite?:(teamId:string|null)=>void; }
export const TeamsDirectory:React.FC<Props>=({teams,drivers=[],selectedSeason,onSelectSeason,availableSeasons=[2026,2025,2024,2023,2022],isLoading,error,favoriteTeamId,onSelectFavorite})=>{
 const [selectedTeam,setSelectedTeam]=useState<Team|null>(null);
 return <div className="f1-info-page"><div className="f1-page-hero"><div><span className="f1-page-kicker">2026 FIA FORMULA 1 WORLD CHAMPIONSHIP</span><h1>TEAMS</h1><p>Constructors, drivers, cars and championship position.</p></div><div className="f1-season-switch">{availableSeasons.map(s=><button key={s} onClick={()=>onSelectSeason(s)} className={selectedSeason===s?'is-active':''}>{s}</button>)}</div></div>
 {isLoading?<div className="f1-empty-card">LOADING CONSTRUCTOR DATA…</div>:error?<EmptyState type="not-found" title="CONSTRUCTOR DATA UNAVAILABLE" message={error}/>:teams.length===0?<EmptyState type="no-data" title="NO CONSTRUCTORS" message="No constructor standings are available."/>:
 <div className="f1-team-grid">{teams.map((t,i)=>{const td=drivers.filter(d=>t.drivers?.includes(d.code));const followed=t.id===favoriteTeamId;return <article key={t.id} className={'f1-team-card '+(followed?'is-followed':'')} style={{'--team-card-color':t.color} as React.CSSProperties} onClick={()=>setSelectedTeam(t)}>
  <div className="f1-team-card-accent"/><div className="f1-team-card-head"><span>P{t.position??i+1}</span><button onClick={e=>{e.stopPropagation();onSelectFavorite?.(followed?null:t.id)}}><Star fill={followed?'currentColor':'none'}/></button></div>
  <div className="f1-team-card-title"><span>{t.powerUnit}</span><h2>{t.name}</h2><p>{t.chassis??'CAR —'}</p></div>
  <div className="f1-team-drivers">{td.slice(0,2).map(d=><div key={d.id}>{d.headshotUrl?<img src={d.headshotUrl} alt="" loading="lazy"/>:<span/>}<b>{d.code}</b></div>)}</div>
  <div className="f1-team-card-stats"><div><span>POINTS</span><strong>{t.points??0}</strong></div><div><span>WINS</span><strong>{t.wins??0}</strong></div><div><span>DRIVERS</span><strong>{td.length||t.drivers?.length||0}</strong></div></div>
 </article>})}</div>}
 {selectedTeam&&<section className="f1-team-profile" style={{'--team-card-color':selectedTeam.color} as React.CSSProperties}><div className="f1-profile-topline"><span style={{color:selectedTeam.color}}>CONSTRUCTOR PROFILE</span><button onClick={()=>setSelectedTeam(null)}><X/></button></div><div className="f1-team-profile-hero"><div className="f1-team-profile-mark" style={{background:selectedTeam.color}}/><div><span>{selectedTeam.powerUnit}</span><h2>{selectedTeam.fullName}</h2><p>{selectedTeam.chassis??'CAR —'} · {selectedTeam.base}</p></div><div className="f1-profile-big-stat"><strong>P{selectedTeam.position??'—'}</strong><span>CHAMPIONSHIP</span></div></div><div className="f1-stat-grid"><div><span>POINTS</span><strong>{selectedTeam.points??0}</strong></div><div><span>WINS</span><strong>{selectedTeam.wins??0}</strong></div><div><span>DRIVERS</span><strong>{selectedTeam.drivers?.join(' / ')||'—'}</strong></div><div><span>POWER UNIT</span><strong>{selectedTeam.powerUnit}</strong></div></div><div className="f1-team-profile-drivers">{drivers.filter(d=>selectedTeam.drivers?.includes(d.code)).map(d=><div key={d.id}>{d.headshotUrl&&<img src={d.headshotUrl} alt="" loading="lazy"/>}<div><b>{d.fullName}</b><span>#{d.number} · {d.code}</span></div></div>)}</div></section>}
 </div>;
};
